#!/bin/bash


if [ $1 == "webm" ]
then
    ffmpeg -video_size 1920x1080 -framerate 25 -f x11grab -i :0.0 -vcodec vp8 ~/Videos/$(date +%d_%B_%Y_%H:%M).webm
fi


if [ $1 == "mkv" ]
then
     ffmpeg -video_size 1920x1080 -framerate 25 -f x11grab -i :0.0 ~/Videos/$(date +%d_%B_%Y_%H:%M).mkv
fi
